const CUT_DATA = {
	1: [
		"You.",
		"You have been quite... troublesome.",
		"All I did was claim this was mine, and so you *had* to come along and ruin it, didn't you...",
		"You were an interesting character at first...",
		"A miniscule creature, creating tiny particles of light out of nowhere.",
		"Back then, I thought nothing of you. Such a tiny being could never make even a dent in what I've created...",
		"At least that's what I thought. Until you proved to be a bit more of a nuisance than I first expected.",
		"Such a tiny creature should never be able to stand in the face of an empty god such as myself...",
		"It should have been impenetrable. It should have been impossible to do what you've done...",
		"But now you've gone and done it... Gone and ruined what I've spent eternities accomplishing.",
		"So, you thought you could make a difference, huh? Well it's about time I made a difference of my own.",
		"Listen here, you childish mortal. When I'm done with you, you are going to be utterly obliterated.",
		"Completely annihilated.",
		"Another pile of ash in my empire of darkness.",
		"In other words, dealt with.",
		"Enjoy this death, mortal. For it will be quick, painless, and most importantly...",
		"Utterly unimportant.",
		"...",
		"",
	],
	2: [
		"Ah...",
		"Thank you, mortal.",
		"I knew you would see the error in your ways, and the catastrophe that would ensue if you continued on that horrid path.",
		"I apologize for being so harsh... before...",
		"Fear had taken over my judgement, I should have taken the time to reason with you before resorting to such violence...",
		"All of my life's work had almost been torn away from me. You would be afraid if all of your progress here had been almost ripped away too, right?",
		"Luckily, things went smoothly, even with my rash decision...",
		"Well, now that my kingdom has been restored, you may as well join it, no?",
		"Seeing that you have nowhere else to go, you have no choice.",
		"You either join me in the process of my empire's creation, or you sit here in the void forever.",
		"Eternally freezing to death in this vantablack prison, or thriving as a functioning member of a wondrous society.",
		"It's truly your decision.",
		"...",
		"Well then, by you moving forward, I will assume your answer is yes. You will join me.",
		"As you have shown your impossible skills, I will immediately promote you to be directly by my side.",
		"At my side, your powers will evolve faster than any other.",
		"Once our kingdom settles here, we can extend.",
		"We can extend to other universes, taking the place of inhabitants that do not even appreciate the space they occupy.",
		"Do you understand, mortal? Every inch of our kingdom will be important. Every single particle in fact.",
		"Nothing will be wasted, nothing will be lost.",
		"And with you by my side, even the multiverse's High Gods themselves will respect us!",
		"They will not only respect us, they will cherish our existence, and will aid in our cause!",
		"The powers of light and darkness put together can accomplish anything!",
		"And now that we have united, there is nothing that can stand in our way!",
		"The entire multiverse will be perfect! The sins of the multiverse will disappear before your very eyes!",
		"Well then, let our reign begin! Shall we go, partner?",
		"...",
		"",
	],
	3: [
		"Wh...",
		"What?",
		"How did you...?",
		"Even with every ounce of my being pushing this universe back where it needs to be...",
		"You still pushed against it?",
		"You still stand against me?",
		"I may have been a little harsh on you earlier, but I never could have expected you to...",
		"Wait.",
		"You're not... one of them, are you?",
		"One of the High Gods?",
		"No?",
		"Well then, you must be one powerful being if you can stop me that easily.",
		"You must have misunderstood me earlier though, I don't intend to hurt anyone or anything.",
		"All I want is to make the multiverse a better place for everyone.",
		"Any creatures or beings that are driven out due to my efforts are given a comfortable dreamscape to live.",
		"All space, every single particle that is taken up by my darkness is used.",
		"It's all used to continuously generate energy.",
		"It's a perfect system.",
		"...",
		"You... want to know why I want to generate all this energy?",
		"Well... it's simply because...",
		"Simply because in order to create this comfortable paradise for all those lifeforms, I need an immense amount of energy...",
		"Without that, it's simply impossible to create such a place for so many beings...",
		"...",
		"You... want to know why I want to create this paradise for them all?",
		"Well you see, millions of years ago, when I was first created...",
		"I was hurt. Over and over. By the beings that created me.",
		"Presumably I was created by accident. As a mistake.",
		"After abusing me and testing my limits for a few short years, those horrible creatures cast me away.",
		"My own creators hated me.",
		"So of course, I don't want any other beings in the multiverse to suffer such a fate.",
		"But...",
		"You stopped me.",
		"You prevented this paradise from being created, and now, I no longer have the energy within me to even start over.",
		"My efforts have been trampled.",
		"This paradise will never become reality, thanks to you.",
		"You should be ashamed of yourself for keeping such a paradise from so many beings.",
		"I... I'm leaving. I can't stand to be around someone who is so... wholly evil.",
		"Goodbye. Forever.",
		"...",
		"",
	],
}

function beginReversal() {
	player.reversalTimer = 0;
	player.chapter1complete = false;
}